### ISSUE TITLE
Installation configuration problem

### ISSUE THREAD

**Issue by haoyunl2** [slimgroup/JutulDarcyRules.jl#28]
I try to install JutulDarcyRules on an Intel i7 x64 processor, and I get a configuration problem with the package CUDA. And I get the following error message.

**(@v1.10) pkg> add JutulDarcyRules
   Resolving package versions...
ERROR: Unsatisfiable requirements detected for package CUDA [052768ef]:
CUDA [052768ef] log:
├─possible versions are: 0.1.0-5.3.4 or uninstalled
├─restricted by julia compatibility requirements to versions: [2.3.0, 2.5.0-5.3.4] or uninstalled
├─restricted by compatibility requirements with LLVM [929cbde3] to versions: 3.3.3-5.3.4 or uninstalled
│ └─LLVM [929cbde3] log:
│   ├─possible versions are: 0.9.0-7.0.0 or uninstalled
│   └─restricted by julia compatibility requirements to versions: 4.0.0-7.0.0 or uninstalled
├─restricted by compatibility requirements with Flux [587475ba] to versions: 2.1.0-4.4.2, leaving only versions: 3.3.3-4.4.2 
 │ └─Flux [587475ba] log:
│   ├─possible versions are: 0.4.1-0.14.15 or uninstalled
│   └─restricted by compatibility requirements with JutulDarcyRules [41f0c4f5] to versions: 0.12.0-0.13.17
│     └─JutulDarcyRules [41f0c4f5] log:
│       ├─possible versions are: 0.2.2-0.2.7 or uninstalled
│       └─restricted to versions * by an explicit requirement, leaving only versions: 0.2.2-0.2.7
└─restricted by compatibility requirements with GPUCompiler [61eb1bfa] to versions: 5.0.0-5.3.4 or uninstalled — no versions left
   └─GPUCompiler [61eb1bfa] log:
     ├─possible versions are: 0.1.0-0.26.4 or uninstalled
     └─restricted by julia compatibility requirements to versions: 0.22.0-0.26.4 or uninstalled**

**Comment by haoyunl2** [comment]
I leave CUDA uninstalled. The above message is updated. I use Julia 1.10, and the configuration problem seems to come from the Flux package requirement for CUDA.

**Comment by ziyiyin97** [comment]
It seems that Flux 0.13 can't be installed due to compatibility issues. Can you try to install Flux 0.13 to verify? If so, I would relax the Flux requirement in Project.toml and open a PR. I do not foresee any hurdle with Flux 0.14. Thanks.

**Comment by haoyunl2** [comment]
Sure, let me give it a try. FYI, adding JutulDarcyRules works on Julia 1.8.

**Comment by haoyunl2** [comment]
Yes. I cannot install Flux 0.13, I get the same error message as below.

(@v1.10) pkg> add [Flux@0.13](mailto:Flux@0.13)
    Updating registry at `C:\Users\haoyun.li\.julia\registries\General.toml`
   Resolving package versions...
ERROR: Unsatisfiable requirements detected for package CUDA [052768ef]:
CUDA [052768ef] log:
├─possible versions are: 0.1.0-5.3.4 or uninstalled
├─restricted by julia compatibility requirements to versions: [2.3.0, 2.5.0-5.3.4] or uninstalled
├─restricted by compatibility requirements with Flux [587475ba] to versions: 3.0.0-4.4.2
│ └─Flux [587475ba] log:
│   ├─possible versions are: 0.4.1-0.14.15 or uninstalled
│   └─restricted to versions 0.13 by an explicit requirement, leaving only versions: 0.13.0-0.13.17
├─restricted by compatibility requirements with LLVM [929cbde3] to versions: 3.3.3-5.3.4 or uninstalled, leaving only versions: 3.3.3-4.4.2
│ └─LLVM [929cbde3] log:
│   ├─possible versions are: 0.9.0-7.0.0 or uninstalled
│   └─restricted by julia compatibility requirements to versions: 4.0.0-7.0.0 or uninstalled
└─restricted by compatibility requirements with GPUCompiler [61eb1bfa] to versions: 5.0.0-5.3.4 or uninstalled — no versions left
   └─GPUCompiler [61eb1bfa] log:
     ├─possible versions are: 0.1.0-0.26.4 or uninstalled
     └─restricted by julia compatibility requirements to versions: 0.22.0-0.26.4 or uninstalled
