### ISSUE TITLE
Register

### ISSUE THREAD

**Issue by ziyiyin97** [slimgroup/JutulDarcyRules.jl#9]
@JuliaRegistrator register()

**Comment by mloubout** [comment]
You are missing the tank workflows for a proper setup

**Comment by ziyiyin97** [comment]
Like these? https://github.com/slimgroup/JutulDarcyAD.jl/pull/10

**Comment by mloubout** [comment]
Yes. CompatHekper is optional. But you need to create the secrets for TagBot so it has the right permissions

**Comment by ziyiyin97** [comment]
@JuliaRegistrator register()

**Comment by ziyiyin97** [comment]
@JuliaRegistrator register()
